import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "500",
    "700",
    "800",
    "900",
  ],
});

export const metadata: Metadata = {
  title: "Auth.js practice",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    // this is prerequisite of using client authjs API🚩🚩🚩
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${poppins.className}  antialiased`}>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
/*
1️⃣ what is Readonly<{ children: React.ReactNode; }>

2️⃣ 

*/
