import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

// this was generated by Shadcn UI
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
